use_frameworks!

target 'XCUITestKit_Example' do
  pod 'XCUITestKit', :path => '../'

  target 'XCUITestKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
