platform :ios, '13.0'
use_frameworks!

target 'XCUITestKit_Example' do
  pod 'XCUITestKit', :path => '../'

  target 'XCUITestKit_UITests' do
    inherit! :none
    pod 'XCUITestLiveReset', :path => '../'
  end
end
