platform :ios, '12.4'
use_frameworks!
inhibit_all_warnings!

project './XCUITestKit.xcodeproj'

inDevelopment = false
target 'XCUITestKit_Example' do
  
  if inDevelopment
    pod 'XCUITestLiveReset/Host', :path => '../'
  else
    pod 'XCUITestLiveReset/Host', '~> 0.1.0'
  end
end

target 'XCUITestKit_UITests' do
  
  if inDevelopment
    pod 'XCUITestLiveReset/Client', :path => '../'
  else
    pod 'XCUITestLiveReset/Client', '~> 0.1.0'
  end
  
end

post_install do |installer|
  installer.generated_projects.each do | project |
    project.targets.each do | target |
      if target.name == 'CNIOBoringSSL' || target.name == 'CNIOBoringSSLShims'
        target.build_configurations.each do | config |
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] ||= ['$(inherited)']
        end
      end
    end
  end
end
