whitelist_rules:
  - unused_closure_parameter
  - fatal_error_message
  - colon
  - file_length
  - identifier_name
  - type_name
  - weak_delegate
  - unowned_variable_capture

excluded:
  - .build
  - "**/.build"
  - "**/Pods"

weak_delegate: warning

type_name:
  min_length: 1
  max_length: 60
  allowed_symbols: ['_']

unowned_variable_capture: warning #i think should change to error
fatal_error_message: warning #i think should change to error

identifier_name:
  min_length: 1
  max_length: 60
  excluded: # excluded via string array
    - id
    - URL
    - vm
  allowed_symbols: "_"

file_length:
  warning: 1200
  error: 3000

indentation: 2

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)