//
//  ValueTypes.swift
//  GRPC_Bonjour_LiveReset
//
//  Created by Darren Lai on 7/7/20.
//  Copyright © 2020 kinwahlai.com. All rights reserved.
//

import Foundation
// TODO: Proper documentation and generated by Jazzy

public enum ValueTypes {
    case stringValue(String)
    case boolValue(Bool)
    case doubleValue(Double)
    case intValue(Int)
}

extension ValueTypes {
    init?(_ input: XCUITestKit_OneOf) {
        guard let valueTypes = input.types else { return nil }
        switch valueTypes {
            case .boolValue(let b):
                self = .boolValue(b)
            case .doubleValue(let d):
                self = .doubleValue(d)
            case .intValue(let i):
                self = .intValue(Int(i))
            case .stringValue(let s):
                self = .stringValue(s)
        }
    }
}

extension ValueTypes {
    func covert() -> XCUITestKit_OneOf {
        var output: XCUITestKit_OneOf = XCUITestKit_OneOf()
        switch self {
            case .boolValue(let b):
                output.types = .boolValue(b)
            case .doubleValue(let d):
                output.types = .doubleValue(d)
            case .intValue(let i):
                output.types = .intValue(Int32(i))
            case .stringValue(let s):
                output.types = .stringValue(s)
        }
        return output
    }
}
