//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: LiveReset.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate XCUITestKit_LiveResetClient, then call methods of this protocol to make API calls.
public protocol XCUITestKit_LiveResetClientProtocol {
  func heartbeat(_ request: XCUITestKit_Echo, callOptions: CallOptions?) -> UnaryCall<XCUITestKit_Echo, XCUITestKit_Echo>
  func reset(_ request: XCUITestKit_Empty, callOptions: CallOptions?) -> UnaryCall<XCUITestKit_Empty, XCUITestKit_Ack>
  func configure(_ request: XCUITestKit_Settings, callOptions: CallOptions?) -> UnaryCall<XCUITestKit_Settings, XCUITestKit_Ack>
}

public final class XCUITestKit_LiveResetClient: GRPCClient, XCUITestKit_LiveResetClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions

  /// Creates a client for the XCUITestKit.LiveReset service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }

  /// Unary call to Heartbeat
  ///
  /// - Parameters:
  ///   - request: Request to send to Heartbeat.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func heartbeat(
    _ request: XCUITestKit_Echo,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<XCUITestKit_Echo, XCUITestKit_Echo> {
    return self.makeUnaryCall(
      path: "/XCUITestKit.LiveReset/Heartbeat",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to Reset
  ///
  /// - Parameters:
  ///   - request: Request to send to Reset.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func reset(
    _ request: XCUITestKit_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<XCUITestKit_Empty, XCUITestKit_Ack> {
    return self.makeUnaryCall(
      path: "/XCUITestKit.LiveReset/Reset",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to Configure
  ///
  /// - Parameters:
  ///   - request: Request to send to Configure.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func configure(
    _ request: XCUITestKit_Settings,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<XCUITestKit_Settings, XCUITestKit_Ack> {
    return self.makeUnaryCall(
      path: "/XCUITestKit.LiveReset/Configure",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

/// To build a server, implement a class that conforms to this protocol.
public protocol XCUITestKit_LiveResetProvider: CallHandlerProvider {
  func heartbeat(request: XCUITestKit_Echo, context: StatusOnlyCallContext) -> EventLoopFuture<XCUITestKit_Echo>
  func reset(request: XCUITestKit_Empty, context: StatusOnlyCallContext) -> EventLoopFuture<XCUITestKit_Ack>
  func configure(request: XCUITestKit_Settings, context: StatusOnlyCallContext) -> EventLoopFuture<XCUITestKit_Ack>
}

extension XCUITestKit_LiveResetProvider {
  public var serviceName: String { return "XCUITestKit.LiveReset" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Heartbeat":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.heartbeat(request: request, context: context)
        }
      }

    case "Reset":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.reset(request: request, context: context)
        }
      }

    case "Configure":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.configure(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}


// Provides conformance to `GRPCPayload`
extension XCUITestKit_Ack: GRPCProtobufPayload {}
extension XCUITestKit_Empty: GRPCProtobufPayload {}
extension XCUITestKit_Settings: GRPCProtobufPayload {}
extension XCUITestKit_OneOf: GRPCProtobufPayload {}
extension XCUITestKit_Echo: GRPCProtobufPayload {}
